// Terminal color themes - similar to SecureCRT
import type { ITheme } from '@xterm/xterm';

export interface TerminalTheme {
  id: string;
  name: string;
  theme: ITheme;
}

export const TERMINAL_THEMES: TerminalTheme[] = [
  {
    id: 'default',
    name: 'Default Dark',
    theme: {
      background: '#1e1e1e',
      foreground: '#cccccc',
      cursor: '#ffffff',
      cursorAccent: '#000000',
      selectionBackground: '#264f78',
      black: '#000000',
      red: '#cd3131',
      green: '#0dbc79',
      yellow: '#e5e510',
      blue: '#2472c8',
      magenta: '#bc3fbc',
      cyan: '#11a8cd',
      white: '#e5e5e5',
      brightBlack: '#666666',
      brightRed: '#f14c4c',
      brightGreen: '#23d18b',
      brightYellow: '#f5f543',
      brightBlue: '#3b8eea',
      brightMagenta: '#d670d6',
      brightCyan: '#29b8db',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    theme: {
      background: '#272822',
      foreground: '#f8f8f2',
      cursor: '#f8f8f0',
      cursorAccent: '#272822',
      selectionBackground: '#49483e',
      black: '#272822',
      red: '#f92672',
      green: '#a6e22e',
      yellow: '#f4bf75',
      blue: '#66d9ef',
      magenta: '#ae81ff',
      cyan: '#a1efe4',
      white: '#f8f8f2',
      brightBlack: '#75715e',
      brightRed: '#f92672',
      brightGreen: '#a6e22e',
      brightYellow: '#f4bf75',
      brightBlue: '#66d9ef',
      brightMagenta: '#ae81ff',
      brightCyan: '#a1efe4',
      brightWhite: '#f9f8f5',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    theme: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      cursorAccent: '#282a36',
      selectionBackground: '#44475a',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    theme: {
      background: '#002b36',
      foreground: '#839496',
      cursor: '#839496',
      cursorAccent: '#002b36',
      selectionBackground: '#073642',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    theme: {
      background: '#fdf6e3',
      foreground: '#657b83',
      cursor: '#657b83',
      cursorAccent: '#fdf6e3',
      selectionBackground: '#eee8d5',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    theme: {
      background: '#2e3440',
      foreground: '#d8dee9',
      cursor: '#d8dee9',
      cursorAccent: '#2e3440',
      selectionBackground: '#434c5e',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    theme: {
      background: '#282828',
      foreground: '#ebdbb2',
      cursor: '#ebdbb2',
      cursorAccent: '#282828',
      selectionBackground: '#504945',
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
    },
  },
  {
    id: 'cisco',
    name: 'Cisco Blue',
    theme: {
      background: '#00274c',
      foreground: '#ffffff',
      cursor: '#00bceb',
      cursorAccent: '#00274c',
      selectionBackground: '#005073',
      black: '#000000',
      red: '#ff5252',
      green: '#00d26a',
      yellow: '#ffc107',
      blue: '#00bceb',
      magenta: '#e040fb',
      cyan: '#00bcd4',
      white: '#ffffff',
      brightBlack: '#546e7a',
      brightRed: '#ff8a80',
      brightGreen: '#69f0ae',
      brightYellow: '#ffd740',
      brightBlue: '#40c4ff',
      brightMagenta: '#ea80fc',
      brightCyan: '#84ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'matrix',
    name: 'Matrix Green',
    theme: {
      background: '#000000',
      foreground: '#00ff00',
      cursor: '#00ff00',
      cursorAccent: '#000000',
      selectionBackground: '#004400',
      black: '#000000',
      red: '#cc0000',
      green: '#00cc00',
      yellow: '#cccc00',
      blue: '#0066cc',
      magenta: '#cc00cc',
      cyan: '#00cccc',
      white: '#00ff00',
      brightBlack: '#006600',
      brightRed: '#ff0000',
      brightGreen: '#00ff00',
      brightYellow: '#ffff00',
      brightBlue: '#0099ff',
      brightMagenta: '#ff00ff',
      brightCyan: '#00ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'retro-amber',
    name: 'Retro Amber',
    theme: {
      background: '#1a1a1a',
      foreground: '#ffb000',
      cursor: '#ffb000',
      cursorAccent: '#1a1a1a',
      selectionBackground: '#4d3300',
      black: '#1a1a1a',
      red: '#ff6600',
      green: '#ffb000',
      yellow: '#ffd000',
      blue: '#cc8800',
      magenta: '#ff9900',
      cyan: '#ffcc00',
      white: '#ffb000',
      brightBlack: '#805500',
      brightRed: '#ff8833',
      brightGreen: '#ffcc33',
      brightYellow: '#ffdd55',
      brightBlue: '#ddaa33',
      brightMagenta: '#ffbb33',
      brightCyan: '#ffdd33',
      brightWhite: '#ffeedd',
    },
  },
  {
    id: 'sunnight',
    name: 'SunNight',
    theme: {
      background: '#000000',
      foreground: '#ffd700',
      cursor: '#ffd700',
      cursorAccent: '#000000',
      selectionBackground: '#4d4d00',
      black: '#000000',
      red: '#ff6b6b',
      green: '#98d85b',
      yellow: '#ffd700',
      blue: '#6bb3ff',
      magenta: '#d98bff',
      cyan: '#5bc0de',
      white: '#ffd700',
      brightBlack: '#666600',
      brightRed: '#ff8a8a',
      brightGreen: '#b5e878',
      brightYellow: '#ffe433',
      brightBlue: '#8ac4ff',
      brightMagenta: '#e5a8ff',
      brightCyan: '#7ad4f0',
      brightWhite: '#ffeb99',
    },
  },
];

// Get theme by ID, fallback to default
export function getTerminalTheme(themeId: string | undefined | null): ITheme {
  const theme = TERMINAL_THEMES.find(t => t.id === themeId);
  return theme?.theme || TERMINAL_THEMES[0].theme;
}

// Custom theme support - merge custom colors with base theme
export interface CustomTerminalTheme {
  baseTheme: string;
  background?: string;
  foreground?: string;
  cursor?: string;
}

export function buildCustomTheme(custom: CustomTerminalTheme): ITheme {
  const base = getTerminalTheme(custom.baseTheme);
  return {
    ...base,
    ...(custom.background && { background: custom.background }),
    ...(custom.foreground && { foreground: custom.foreground }),
    ...(custom.cursor && { cursor: custom.cursor }),
  };
}
